#!/usr/bin/env python3
"""Build and check the IJOC submission: one document, no supplement.

`paper/ijoc/paper.tex` is the manuscript. This script builds it, checks it
against the IJOC length policy, and writes a flattened single-file source with
every generated table and the bibliography inlined.

The policy (Submission Guidelines, "Length Policy", May 2025) is that a paper
may not exceed 25 pages including references, tables and graphs. This paper
carries no appendix at all: the proofs sit beside the statements they prove and
the limitations table sits in the discussion, so the whole submission is one
continuous document and the check is:

    body pages + reference pages   <= 25
    appendix pages                 == 0

Usage:
    python Code/scripts/build_submission.py            # build and check
    python Code/scripts/build_submission.py --keep-aux # leave latexmk files
"""
from __future__ import annotations

import argparse
import pathlib
import re
import subprocess
import sys

# ----------------------------------------------------------------------
# Where the manuscript lives. In this working tree it is a sibling of Code/;
# in a standalone clone of the artifact it is expected in-tree under paper/.
# Resolving it here keeps a clean clone from silently writing to nowhere.
# ----------------------------------------------------------------------
def manuscript_dir() -> pathlib.Path:
    here = pathlib.Path(__file__).resolve()
    for base in (here.parents[1], here.parents[2]):
        cand = base / "paper" / "ijoc"
        if (cand / "paper.tex").exists():
            return cand
    raise SystemExit(
        "paper/ijoc/paper.tex not found, neither in this repository nor "
        "beside it. The manuscript directory is not part of this artifact; "
        "see README.md."
    )


SRC = manuscript_dir()

MAX_COUNTED_PAGES = 25   # body + references + tables + graphs

AUX_SUFFIXES = (".aux", ".log", ".out", ".fls", ".fdb_latexmk", ".blg",
                ".synctex.gz", ".spl", ".loa")

CHECKS = [
    (r"Reference `[^']+' on page .* undefined", "undefined reference"),
    (r"Citation `[^']+' on page .* undefined", "undefined citation"),
    (r"Label `[^']+' multiply defined", "multiply defined label"),
    (r"Overfull \\hbox", "overfull hbox"),
]


def die(msg):
    sys.exit(f"build_submission: {msg}")


def latexmk(stem, cwd):
    r = subprocess.run(["latexmk", "-pdf", "-interaction=nonstopmode",
                        f"{stem}.tex"], cwd=cwd, capture_output=True, text=True)
    if not (cwd / f"{stem}.pdf").exists():
        sys.stderr.write(r.stdout[-4000:] + r.stderr[-2000:])
        die(f"{stem}.tex did not produce a PDF")
    log = cwd / f"{stem}.log"
    return log.read_text(errors="replace") if log.exists() else ""


def page_text(pdf, pg):
    return subprocess.run(["pdftotext", "-f", str(pg), "-l", str(pg),
                           str(pdf), "-"], capture_output=True,
                          text=True).stdout


def n_pages(pdf):
    out = subprocess.run(["pdfinfo", str(pdf)], capture_output=True,
                         text=True).stdout
    for line in out.splitlines():
        if line.startswith("Pages:"):
            return int(line.split()[1])
    die(f"cannot read the page count of {pdf}")


def classify(pdf):
    """Split the page range into body and reference pages."""
    total = n_pages(pdf)
    # No appendix: the submission is one continuous document. The reference
    # list is the trailing run of pages that look like a bibliography, which
    # the class sets single-spaced and which is dense in "(year)" citations.
    def is_refs(pg):
        t = page_text(pdf, pg)
        return bool(re.search(r"\(\d{4}[a-z]?\)", t)) and t.count("(") > 12

    for pg in range(1, total + 1):
        if "Appendix A:" in page_text(pdf, pg):
            die(f"page {pg} starts an appendix; this submission carries none")

    first_ref = next((pg for pg in range(1, total + 1)
                      if page_text(pdf, pg).lstrip().startswith("References")
                      or "\nReferences\n" in page_text(pdf, pg)), None)
    if first_ref is None:
        die("no reference pages found; adjust the classifier")
    if not any(is_refs(pg) for pg in range(first_ref, total + 1)):
        die(f"the References heading is on page {first_ref} but no page after "
            f"it looks like a bibliography")
    refs = list(range(first_ref, total + 1))
    body = list(range(1, first_ref))
    return total, body, refs


def flatten():
    """paper_flat.tex: paper.tex with every \\input and the bbl inlined."""
    text = (SRC / "paper.tex").read_text()

    def expand(m):
        name = m.group(1)
        f = SRC / (name if name.endswith(".tex") else name + ".tex")
        return ("%% ---- begin inlined %s (generated by the analysis scripts)"
                " ----\n%s\n%%%% ---- end inlined %s ----"
                % (f.name, f.read_text().rstrip(), f.name))

    text = re.sub(r"\\input\{([^}]+)\}", expand, text)
    bbl = SRC / "paper.bbl"
    if bbl.exists():
        text = text.replace(
            "\\bibliographystyle{informs2014}\n\\bibliography{references}",
            "%% ---- begin inlined paper.bbl ----\n"
            + bbl.read_text().rstrip() + "\n%% ---- end inlined paper.bbl ----")
    (SRC / "paper_flat.tex").write_text(
        "%% GENERATED by Code/scripts/build_submission.py from paper.tex.\n"
        "%% Flattened single file: every \\input and the bibliography inlined.\n"
        + text)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--keep-aux", action="store_true")
    args = ap.parse_args()

    if not (SRC / "paper.tex").exists():
        die(f"{SRC / 'paper.tex'} not found")
    log = latexmk("paper", SRC)
    flatten()

    total, body, refs = classify(SRC / "paper.pdf")
    counted = len(body) + len(refs)
    print(f"  paper.pdf : {total} pages")
    print(f"    body {body[0]}-{body[-1]} + references {refs[0]}-{refs[-1]}"
          f" = {counted} counted  (IJOC limit {MAX_COUNTED_PAGES})")

    problems = []
    for pat, what in CHECKS:
        hits = re.findall(pat, log)
        if hits:
            problems.append(f"{len(hits)} {what}(s)")
    if counted > MAX_COUNTED_PAGES:
        problems.append(f"{counted} counted pages, "
                        f"{counted - MAX_COUNTED_PAGES} over the IJOC limit")

    if not args.keep_aux:
        for f in SRC.iterdir():
            if f.suffix in AUX_SUFFIXES and f.stem in ("paper", "paper_flat"):
                f.unlink()

    if problems:
        print("\nPROBLEMS")
        for x in problems:
            print("  -", x)
        sys.exit(1)
    print("\nOK: one document, no appendix, within the IJOC page limit.")


if __name__ == "__main__":
    main()
